### ISSUE TITLE
TypeError: Cannot read property 'overrideMbc' of undefined

### ISSUE THREAD

**Issue by wilhg** [rauchg/gameboy#1]
when I run "node index.js", it throw the bug below:

TypeError: Cannot read property 'overrideMbc' of undefined
at Array.GameBoyCore.memoryWriteMBCRAM (/home/cuebyte/workspaces/weplay-emulator/node_modules/gameboy/index.js:8376:48)
at Array.GameBoyCore.OPCODE.parentObj.stackPointer as 50
at GameBoyCore.executeIteration (/home/cuebyte/workspaces/weplay-emulator/node_modules/gameboy/index.js:5867:33)
at GameBoyCore.run (/home/cuebyte/workspaces/weplay-emulator/node_modules/gameboy/index.js:5809:16)
at wrapper as _onTimeout
at Timer.listOnTimeout as ontimeout

is this the bug of gameboy? how to fix it?

**Comment by vogelito** [comment]
Hi cuebyte, where you able to get around this issue? I'm getting the same error, although the traceback is slightly different:

```
TypeError: Cannot read property 'overrideMbc' of undefined
    at Array.GameBoyCore.memoryWriteMBCRAM (/home/ubuntu/socket.io/weplay-emulator/node_modules/gameboy/index.js:8375:48)
    at Array.GameBoyCore.OPCODE.parentObj.stackPointer [as 50] (/home/ubuntu/socket.io/weplay-emulator/node_modules/gameboy/index.js:729:50)
    at GameBoyCore.executeIteration (/home/ubuntu/socket.io/weplay-emulator/node_modules/gameboy/index.js:5867:33)
    at GameBoyCore.run (/home/ubuntu/socket.io/weplay-emulator/node_modules/gameboy/index.js:5809:16)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```
